### ISSUE TITLE
Page not found - rda_project_setting

### ISSUE THREAD

**Issue by AndrewHoole** [ozguryazilimas/redmine_default_assignee#14] opened 2023-02-03 15:02 UTC
Hi, 

Trying to use this plugin with Redmine Version 5(bitnami OVA installation on VMWare VM). I see the **Default Assignee** tab in my project which is displaying under URL ..projects/ProjectName/settings/rda_project_settings but when I click on Save I get a Page not found error for page ...projects/ProjectName/rda_project_settings. 

Do you have any idea why this is happening? 

Thanks

Andrew

**Comment by zaburt** [comment] 2023-02-04 22:50
Tried a different plugin initializer, it works for me now with Redmine 5.0.4. Can you verify that it works for you too ?

**Comment by ashrafalzyoud** [comment] 2023-02-05 20:36
hi thx for your plugin
same error
```
[7c7f53b4-6778-4cbe-b84f-36bba48f8770] AbstractController::ActionNotFound (The action 'rda_project_settings' could not be found for ProjectsController
Did you mean?  render_tags_list
               link_to_project_settings
               parse_sections
               render_project_nested_lists):
```

**Comment by ashrafalzyoud** [comment] 2023-02-05 20:55
when im delete redmineup_tags its work and show status per project
but then new error
```
[33231b62-695b-4df7-980f-198ad5dcfc95] AbstractController::ActionNotFound (The action 'rda_project_settings' could not be found for ProjectsController
Did you mean?  link_to_project_settings
               parse_sections
               render_project_nested_lists
               product_tag_links):
```

can u work with compitable with redmineup plugins plz
@zaburt

**Comment by ashrafalzyoud** [comment] 2023-02-05 21:00
when im delete redmineup_tags and redmine_products
another error
```
Did you mean?  link_to_project_settings
               parse_sections
               render_project_nested_lists
               _project_news_path):
```

**Comment by zaburt** [comment] 2023-02-06 08:49
I have made a change on how projects controller is patched, it should work with RedmineUP now. If it does not work I would think it is an issue at RedmineUP side though as I have been testing this plugin on an environment with 10+ other plugins without issues.

**Comment by AndrewHoole** [comment] 2023-02-06 08:55
Zaburt thanks for your work on this. I'll try again but can I just check I'm installing it correctly. I have been doing the following:
- clone github repo into redmine/plugins directory
- in the redmine directory run the RAILS_ENV=production bundle command
- restart redmine

**Comment by AndrewHoole** [comment] 2023-02-06 09:08
It is working for me now.

**Comment by zaburt** [comment] 2023-02-06 09:24
@AndrewHoole you are installing correctly, you just need to run the plugin migrate too

```
RAILS_ENV=production bundle exec rake redmine:plugins:migrate
```

There was a bug when you opened the story, thank you for reporting. The issue is fixed now so closing the story.

**Closed as completed by zaburt** 2023-02-06 09:24 UTC
